#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Oct 09 23:36:11 KST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=Sildur's Vibrant Shaders v2.02 Lite.zip
